version: '3'
services:
  postgres-nest:
    image: postgres:15-alpine
    container_name: postgres-nest
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Rose9840503594
      POSTGRES_DB: codemonkey
    volumes:
      - ./data:/var/lib/postgresql/data

  app:
    build: .
    container_name: codemonkey-app
    ports:
      - "3001:3000"
    environment:
      DATABASE_URL: postgresql://postgres:Rose9840503594@postgres-nest:5432/codemonkey
    depends_on:
      - postgres-nest
